import { SiteHeader } from "../../../SiteHeader";
import { sitePath } from "../../../site-path";
import styles from "./tracet.module.css";
export const metadata={title:"ZYRO_AI_TRACET | CV610 AI Vision Tracking Module · Future Product",description:"CV610 AI vision concept, planned recognition and tracking functions, four configurations and target interfaces. Future product; final details pending."};
const artwork="/products/zyro-ai-tracet-overview.png";
function Artwork({x,y,width,height,alt,eager=false}:{x:number;y:number;width:number;height:number;alt:string;eager?:boolean}){return <div className={styles.artwork} style={{aspectRatio:`${width} / ${height}`}}><img src={sitePath(artwork)} alt={alt} loading={eager?"eager":"lazy"} style={{width:`${941/width*100}%`,maxWidth:"none",left:`${-x/width*100}%`,top:`${-y/height*100}%`}}/></div>;}
const features=[
  ["Multi-target recognition","Planned detection and filtering of people, vehicles and aircraft."],
  ["Assisted crosshair selection","The crosshair is planned to snap to a nearby detected subject for easier selection."],
  ["Occlusion recovery","Past trajectory information is planned to help reacquire a temporarily obscured subject."],
  ["Target reacquisition","A planned search-area function may locate a subject again after tracking is lost."],
  ["Picture-in-picture display","Planned wide and telephoto views combine scene context and detail."],
  ["Thermal-imaging option","An optional USB thermal module is proposed for varied lighting conditions."],
];
const versions=[
  {name:"S",lens:"Single visible-light lens · 4 mm",copy:"Lightweight configuration for general observation.",x:82,y:1134,width:110,height:77},
  {name:"D-Lite",lens:"Dual visible-light lenses · 4 mm + 12 mm",copy:"Wide and telephoto views in one configuration.",x:276,y:1136,width:164,height:79},
  {name:"ST",lens:"Visible-light + thermal",copy:"Two imaging modes for day and night observation.",x:500,y:1135,width:161,height:80},
  {name:"DT-Lite",lens:"Dual visible-light + thermal",copy:"A multi-view configuration for broader observation needs.",x:710,y:1134,width:179,height:82},
];
const specs=[["Main processor","Hi3516CV610"],["NPU capacity","1 TOPS (concept-sheet figure)"],["Video output","1920 × 1080 @ 30 fps"],["AI input","640 × 640"],["Detection frame rate","10–15 fps"],["Tracking frame rate","30 fps"],["Input voltage","9–16 V"],["Mounting-hole spacing","25.5 × 25.5 mm"],["Interfaces / protocols","CRSF / MAVLink / USB Thermal"]];
export default function AiTracet(){return <><SiteHeader language="en"/><main className={styles.page} lang="en">
  <nav className={styles.subnav} aria-label="Product navigation"><a href={sitePath("/wiki/future-products/")}>← Future products</a><div><a href="#architecture">Architecture</a><a href="#features">Features</a><a href="#versions">Versions</a><a href="#specs">Target specifications</a></div></nav>
  <section className={styles.hero}><div className={styles.heroCopy}><span className={styles.eyebrow}>FUTURE PRODUCT / AI VISION</span><h1>ZYRO_AI_TRACET</h1><h2><em>CV610</em> AI vision tracking module</h2><p>A Hi3516CV610-based vision-recognition and tracking concept</p><div className={styles.keywords}>Recognition / Tracking / Compact design / Open protocols</div></div><Artwork x={0} y={137} width={941} height={275} alt="Concept artwork showing the CV610 processing board, visible-light and thermal lenses, and aerial observation" eager/><div className={styles.metrics}>{[["Hi3516CV610","Main processor"],["1 TOPS","Planned NPU capacity"],["1080P30","Target video output"],["CRSF / MAVLink","Proposed protocols"]].map(([v,l])=><div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div></section>
  <div className={styles.status}><strong>Future product · Not yet launched</strong><p>This page is based on the supplied concept artwork. Functions, design and specifications remain planned; final versions, compatibility and field performance require confirmation.</p></div>
  <section id="architecture" className={styles.section}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>01 / SYSTEM ARCHITECTURE</span><h2>From sensing to recognition and response.</h2></div><p>Proposed architecture combining detection, selection, tracking and picture-in-picture display.</p></div><div className={styles.architecture}>{[
    {title:"Visible-light / thermal cameras",copy:"Wide-angle · Telephoto · Thermal",x:48,y:610,width:164,height:81},
    {title:"CV610 AI processing board",copy:"Detect · Select · Track · Combine",x:306,y:591,width:144,height:103},
    {title:"Flight controller / gimbal",copy:"Proposed tracking commands",x:521,y:610,width:150,height:85},
    {title:"Video link / display",copy:"Live video · Picture-in-picture display",x:739,y:610,width:153,height:85},
  ].map((a,i)=><article key={a.title}><span className={styles.eyebrow}>0{i+1}</span><Artwork {...a} alt={a.title+" concept illustration"}/><h3>{a.title}</h3><p>{a.copy}</p></article>)}</div></section>
  <section id="features" className={`${styles.section} ${styles.alternate}`}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>02 / INTELLIGENT VISION</span><h2>A connected recognition and tracking workflow.</h2></div><p>Six planned functions for subject selection, continued tracking and multi-view observation.</p></div><div className={styles.features}>{features.map(([t,d],i)=><article key={t}><span className={styles.number}>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
  <section id="versions" className={styles.section}><div className={styles.sectionTitle}><div><span className={styles.eyebrow}>03 / PLANNED VERSIONS</span><h2>Four planned configurations, different views.</h2></div><p>Versions are grouped by lens combination; final package contents are pending.</p></div><div className={styles.versions}>{versions.map(v=><article key={v.name}><h3>{v.name}</h3><p className={styles.lens}>{v.lens}</p><Artwork {...v} alt={v.name+" lens configuration concept"}/><p>{v.copy}</p></article>)}</div></section>
  <section id="specs" className={`${styles.section} ${styles.alternate}`}><div className={styles.specLayout}><div><span className={styles.eyebrow}>04 / TARGET SPECIFICATIONS</span><h2>Target specifications</h2><p>The figures follow the concept sheet; detection and tracking frame rates are listed separately.</p><dl className={styles.specs}>{specs.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className={styles.note}>Processing, frame rates and output depend on algorithms, lenses, inputs and hardware revision. Thermal imaging is optional; compatible modules remain to be confirmed.</p></div><div className={styles.applications}><span className={styles.eyebrow}>05 / APPLICATION SCENARIOS</span><h2>For a wider range of observation tasks</h2>{[
    {title:"Aerial observation",copy:"Search and rescue, power inspection and environmental monitoring.",x:414,y:1314,width:147,height:99},
    {title:"Moving-subject observation",copy:"Visual detection and monitoring of moving people and vehicles.",x:584,y:1314,width:148,height:99},
    {title:"Day and night observation",copy:"Visible-light and thermal options for different lighting conditions.",x:757,y:1314,width:146,height:99},
  ].map(a=><article key={a.title}><Artwork {...a} alt={a.title+" scenario concept"}/><div><h3>{a.title}</h3><p>{a.copy}</p></div></article>)}</div></div></section>
  <section className={styles.contact}><span className={styles.eyebrow}>A SMARTER VIEW, A WIDER WORLD</span><h2>Compact AI vision,<br/>more observation possibilities.</h2><p>Discuss lens combinations, platform interfaces and real application requirements.</p><div className={styles.actions}><a className={styles.button} href="mailto:song_uestc@126.com?subject=ZYRO_AI_TRACET">Discuss requirements ↗</a><a href={sitePath(artwork)} target="_blank" rel="noreferrer">View full concept artwork ↗</a></div><p className={styles.note}>Source: CV610 AI vision tracking concept artwork. Illustrated scenes and interfaces are not field-test results.</p></section>
  <footer className={styles.footer}><a href={sitePath("/wiki/future-products/")}>ZYRO / Future products</a><a href="mailto:song_uestc@126.com">song_uestc@126.com</a><a href="https://wa.me/8613480720937">WhatsApp +86 134 8072 0937</a><a href="https://www.zyrolink.cn">www.zyrolink.cn</a></footer>
</main></>;}
