export type EnglishArticle = { slug: string; tag: string; title: string; deck: string; date: string; read: string; body: string };
export const englishArticles: EnglishArticle[] = [
  {
    slug: "antenna-gain-beamwidth-en", tag: "RF fundamentals", title: "Does higher dBi always mean more range? Antenna gain and beamwidth", date: "2026.09.14", read: "6 min read",
    deck: "Antenna gain concentrates existing RF energy in particular directions; it does not increase transmitter output power.",
    body: `# Does higher dBi always mean more range? Antenna gain and beamwidth

Replacing a small omnidirectional antenna with a higher-gain one may improve a link when it points at the receiver, yet the signal can fade sooner as the aircraft turns or moves to the side. Gain and angular coverage must be considered together.

## What does dBi measure?

dBi expresses antenna gain relative to an ideal isotropic radiator that distributes energy equally in every direction. A real antenna has a radiation pattern: it sends and receives more strongly in some directions than in others. A higher dBi number describes a peak in that pattern, not extra power generated by the transmitter. Feed-line loss, antenna efficiency and impedance matching can also reduce the practical benefit.

## Gain and the main beam

The main lobe is the strongest radiation direction. The 3 dB beamwidth is the angular span between points where power has fallen to half the peak. It is a reference point, not a hard boundary beyond which reception stops. A narrow beam can add link margin on a fixed route but is more sensitive to pointing errors, aircraft attitude and ground-station movement.

| Claim | Better interpretation |
| --- | --- |
| Higher dBi reaches farther in every direction | Gain is concentrated in part of the radiation pattern. |
| No signal exists outside the 3 dB beam | The pattern continues beyond that reference angle. |
| A high-gain antenna fixes all stutter | Obstructions, polarization mismatch, interference and receiver condition still matter. |

## How to choose

First define whether the receiver must cover all directions, a sector or a fixed path. Then read both horizontal and vertical radiation patterns, polarization and side lobes. Account for mounting and expected pitch, roll and turns. Finally, record signal and video along the actual route at the intended distance and altitude. A wide pattern often gives better attitude tolerance; a narrow directional pattern is most useful when the target direction is known and alignment is reliable.

[ZYRO C403 Max product brief](../../downloads/zyro-c403-max.pdf)`
  },
  {
    slug: "rolling-shutter", tag: "Imaging fundamentals", title: "Why do straight objects lean during fast camera movement? Rolling shutter", date: "2026.09.07", read: "6 min read",
    deck: "Different sensor rows capture different instants; motion during readout can distort the shape of a single frame.",
    body: `# Why do straight objects lean during fast camera movement? Rolling shutter

During a fast sideways move, a light pole or building edge can seem to lean. This is often an imaging-timing effect rather than a radio-link fault. A video frame is not always captured at one instant.

## A frame assembled line by line

Many CMOS sensors expose or read image rows in sequence. The top and bottom rows therefore represent slightly different moments. If the camera or subject moves during that interval, the final image combines different positions. Fast lateral movement can slant vertical lines; rotating blades or wheels can appear bent or fragmented. This differs from lens distortion and from a whole frame that freezes or breaks into compression blocks.

| Appearance | Likely cause | Check first |
| --- | --- | --- |
| Straight pole leans only during a sideways move | Row-by-row capture and relative motion | Motion, subject distance and sensor readout |
| Wide-angle edges bulge even while stationary | Lens distortion or correction | Field of view and lens settings |
| Whole frame freezes or becomes blocky | Encoder, radio or receiver instability | Bitrate, signal, antennas and receiver |

## What makes it more visible?

The important quantity is how far the scene moves during sensor readout. Nearby objects change position faster in the image than distant ones. Rapid yaw, vibration and rotating subjects also increase visible artifacts. Higher frame rate alone does not guarantee that rolling-shutter distortion disappears; readout mode, exposure, motion and stabilization all influence the result.

## Reducing the effect

Leave more distance from close vertical structures during fast movement, stabilize the airframe and camera mount, and test with repeatable passes by poles or a grid. For tasks involving fast-object measurement or precise geometry, consider whether a global-shutter sensor is required. Global shutter samples all pixels at the same instant and avoids this particular row-timing deformation, although ordinary motion blur can still occur.

![Rolling-shutter scan and motion illustration from the original technical article](../../products/rolling-shutter-scan.png)

The original illustration contains Chinese labels; its English explanation is given above. [ZYRO Cam product brief](../../downloads/zyro-cam.pdf)`
  },
  {
    slug: "fpv-osd-basics", tag: "Flight information", title: "Where does the text on an FPV image come from? Understanding OSD", date: "2026.08.24", read: "6 min read",
    deck: "An on-screen display turns flight-controller data into readable status on a live camera image.",
    body: `# Where does the text on an FPV image come from? Understanding OSD

Voltage, current, flight mode and direction indicators on an FPV picture do not originate in the camera lens. On-screen display (OSD) combines a live image with status information supplied by the flight controller and other sensors.

## Follow the data path

The flight controller collects measurements and state such as battery voltage, current, GPS information, warnings and flight mode. It sends relevant values to an OSD processor or to a digital-video system that draws text and symbols over the image. The video transmitter then sends the combined picture. Some receiver or ground-station overlays may be drawn at the receiving end instead; the location depends on the system.

This separation matters when troubleshooting. If the camera image is clear but a status value is wrong, inspect the data source, protocol and OSD configuration. If both image and overlay freeze together, look at the video path. If only the overlay disappears, check the telemetry connection and layout settings before replacing the camera.

## Which fields help?

Battery voltage and current indicate remaining power and load. Flight mode and arming state explain how controls will behave. Link-status or signal indicators help distinguish an aircraft issue from a video issue. GPS-related direction and distance fields are meaningful only when their sensors have a valid fix and are configured correctly. Units, alarms and field positions should be checked during setup rather than trusted from their mere appearance on screen.

![Flight-controller data path to an FPV on-screen display](../../products/fpv-osd-data-path.png)

The original illustration has Chinese labels; this article describes the same data path in English. A useful setup check is to compare on-screen values with the flight controller's own readout while the aircraft is safely stationary.`
  },
  {
    slug: "fov-and-distortion", tag: "Imaging fundamentals", title: "Why do wide-angle images bend near the edges? FOV and lens distortion", date: "2026.08.20", read: "6 min read",
    deck: "A wide field of view captures more surroundings, but lens projection can change how straight lines and distances appear.",
    body: `# Why do wide-angle images bend near the edges? FOV and lens distortion

A wide FPV view helps a pilot see obstacles around the flight path, yet straight lines near the frame edge can bow outward. Field of view (FOV) and lens distortion describe related but different properties.

## FOV is coverage; distortion is geometry

FOV is the angular extent of the scene recorded by a lens and sensor. It depends on focal length, sensor size and any digital crop. A shorter focal length on the same sensor generally shows more of the surroundings. Distortion describes how points are mapped from the scene to the image. Barrel distortion bends straight lines outward near the edges; a correction algorithm can straighten them but often crops or stretches part of the picture.

A quoted diagonal FOV is not the same as horizontal or vertical FOV. Compare the same axis and sensor mode when evaluating cameras. A 16:9 crop, resolution mode or stabilization crop can narrow the usable image even if the lens itself is unchanged.

Perspective is another source of apparent shape change: nearby objects look much larger than distant ones even through a corrected lens. Camera tilt changes the horizon position. These effects should not automatically be diagnosed as lens distortion.

## Choose for the task

For fast FPV, wide coverage can improve awareness, but judge whether edge distortion interferes with steering cues. For inspection, measurement or target identification, central detail, calibration and consistent projection may matter more than maximum angle. Compare sample images of a grid or building façade at the intended distance, check correction settings and mount angle, and repeat the test in the chosen video mode.

![ZYRO Cam FPV camera](../../products/cam.jpg)

The lens must be evaluated together with its sensor, image pipeline and final display; one FOV number cannot describe the complete viewing experience.`
  },
  {
    slug: "fresnel-zone", tag: "RF fundamentals", title: "Why a visible path can still have a weak link: the Fresnel zone", date: "2026.08.17", read: "6 min read",
    deck: "Radio waves need clearance around the direct line between antennas, not merely a thin visible sight line.",
    body: `# Why a visible path can still have a weak link: the Fresnel zone

Two antennas may see each other while a tree canopy, roof or ridge still reduces signal quality. The direct line is only part of the space used by radio propagation.

## The first Fresnel zone

The first Fresnel zone is an ellipsoidal region around the straight path from transmitter to receiver. Waves taking nearby paths can combine constructively at the receiver. An obstruction inside this region can attenuate or diffract them even when it does not fully block the straight sight line. The zone is widest near the middle of the path; its size increases with distance and with wavelength.

A common planning approximation aims to keep a substantial part of the first zone clear, rather than assuming that optical visibility is enough. The precise clearance target depends on the link and terrain. At a field site, account for tree growth, roofs, land curvature, antenna height and the aircraft's changing altitude.

For intuition, the midpoint of a 1 km path at 5.8 GHz has a first-Fresnel-zone radius of roughly 3.6 m in a simple free-space calculation. The radius changes with frequency and geometry; a thin visual sight line is therefore not enough.

## Field checks

Mark both antenna locations and their heights. Inspect the terrain profile, not only a map's straight distance. Note structures and vegetation near the midpoint. If signal changes sharply when an antenna is raised, partial Fresnel-zone obstruction may be involved, though interference or alignment should also be checked. Compare measurements at repeatable locations before drawing a conclusion.

![ZYRO C403 Max digital video-link hardware](../../products/c403.jpg)

The useful question is whether there is enough open space around the RF path at the actual frequency, height and range—not just whether the other antenna is visible.`
  },
  {
    slug: "vtx-antenna-safety", tag: "Analog video basics", title: "Why must a video transmitter have an antenna before transmitting?", date: "2026.08.10", read: "6 min read",
    deck: "A missing or mismatched antenna can reflect RF power toward a transmitter's output stage.",
    body: `# Why must a video transmitter have an antenna before transmitting?

An RF transmitter expects a suitable antenna and feed line. If the antenna is absent, loose, damaged or mismatched, some power can be reflected back toward the output stage. Higher power and longer operation increase stress and heat.

## Forward and reflected power

A matched load absorbs delivered power. A mismatch raises reflected power and standing-wave ratio. This does not imply that every brief mismatch causes immediate failure; it means the unit is outside its intended load condition. Follow the manual for the specific device rather than assuming that a brief low-power test is harmless.

An attached antenna may still be unsuitable if designed for another band, fitted through a poor adapter, connected through damaged coax or mounted against conductive material. “Connected” and “properly matched” are separate checks.

## Before applying power

Confirm the correct connector and frequency-band antenna. Seat it securely, inspect the coax and adapters, and ensure the antenna is not trapped against conductive structure. Check channel and power mode. If the link is unexpectedly weak or the transmitter runs hot, inspect the RF path before increasing power.

![3 W video-transmitter module](../../products/tx3w.jpg)

The antenna is a functional part of the system, not an optional accessory.`
  },
  {
    slug: "wdr-backlight", tag: "Imaging fundamentals", title: "Why does backlit FPV footage lose detail? Understanding WDR", date: "2026.07.30", read: "6 min read",
    deck: "Wide dynamic range helps a camera retain useful detail when bright and dark regions share one frame.",
    body: `# Why does backlit FPV footage lose detail? Understanding WDR

A camera pointing toward bright sky may render the ground nearly black. Exposing for the ground can instead clip the sky to white. A sensor has limited dynamic range: only a finite span between the darkest and brightest levels it can record with usable detail.

## What WDR does

Wide dynamic range (WDR) methods may combine exposure information, use a sensor mode with more range, or tone-map different areas of the picture. The implementation differs by camera. WDR cannot recover pixels already saturated by very bright light or details buried in noisy shadows. Strong tone mapping can flatten contrast; multi-exposure processing can create artifacts around moving objects.

## Compare in the intended scene

Record the same backlit route with repeatable movement. Look for readable ground objects, highlight detail, motion artifacts and response time, not only a brighter preview. Lens flare, dirty glass and unsuitable exposure settings are separate problems. Confirm the camera's WDR mode before comparing footage.

![ZYRO Cam FPV camera](../../products/cam.jpg)

The useful result is interpretable detail in the parts of the scene that matter to the task.`
  },
  {
    slug: "antenna-diversity", tag: "RF fundamentals", title: "Why two receive antennas do not double range: diversity reception", date: "2026.07.28", read: "6 min read",
    deck: "Diversity gives a receiver another path when reflections or orientation create a deep signal fade.",
    body: `# Why two receive antennas do not double range: diversity reception

A moving aircraft changes antenna orientation and the way direct and reflected waves arrive. At some positions these waves combine poorly, causing a deep fade even though the average path is viable. A second antenna in another location or orientation may avoid that fade.

## How diversity helps

Depending on receiver design, diversity can select the stronger path or combine paths. Spatial separation, polarization and pattern differences reduce the chance that both paths fade together. This can improve continuity; it does not guarantee twice the range. Two poorly installed antennas may still fail at the same time.

The peak gains of two antennas cannot simply be added. Diversity changes the chance of preserving a usable receive path; the actual selected or combined signal and receiver design still determine link performance.

## Check the installation

Keep antennas clear of metal and other shielding. Follow spacing and polarization guidance, inspect both connectors, and confirm that each receiver input is active. A directional-plus-omnidirectional setup serves different parts of a route, so test it while the aircraft moves. Record signal and image interruptions along the same path before and after changing placement.

![ZYRO C403 Max digital video-link hardware](../../products/c403.jpg)

Frequency interference, insufficient link margin and terrain obstruction still need their own investigation.`
  },
  {
    slug: "analog-frequency-planning", tag: "Analog video basics", title: "Choosing analog FPV channels: bands, channels and interference", date: "2026.07.27", read: "7 min read",
    deck: "A repeatable channel plan starts with actual frequencies and enough separation for every transmitter at the site.",
    body: `# Choosing analog FPV channels: bands, channels and interference

Two analog FPV transmitters can interfere even when their channel names differ. A band is a group of assignments; the useful planning value is the actual center frequency and occupied spectrum of each signal.

## Read the frequency table

Use the table for the specific transmitter and receiver. The same letter or number may denote a different frequency on another device. Check that the antenna supports the selected frequency and that its use follows applicable local rules.

## Leave usable separation

Analog video occupies more than a single mathematical frequency. Nearby signals, harmonics, receiver overload and high-power equipment can affect other channels. Necessary spacing depends on filters, modulation, power, antenna isolation and local RF noise. For a group of aircraft, label channel assignments before powering all transmitters.

The number of selectable channel names does not equal the number of simultaneous links a site can support. Nominally different channels can overlap in practice, especially near high-power transmitters.

## Verify at the site

Scan the band where the system will operate. Test one transmitter at a time and then the group. If a picture degrades, check actual frequencies, antennas and physical isolation before increasing power. Log the arrangement and observations so it can be reproduced.

![ZYRO Air Analog FPV product](../../products/air-analog.jpg)

A channel plan is a site-specific compatibility check, not merely a list of unused names.`
  },
  {
    slug: "antenna-polarization", tag: "RF fundamentals", title: "Why antenna polarization and orientation affect video quality", date: "2026.07.27", read: "7 min read",
    deck: "A radio link depends on compatible antenna polarization and clear radiation paths as the aircraft moves.",
    body: `# Why antenna polarization and orientation affect video quality

A link can fade during a turn even if the aircraft is barely farther away. Polarization, radiation pattern and airframe shielding can all contribute.

## Linear and circular polarization

Linear polarization describes the electric field's orientation, such as vertical or horizontal. Linear antennas are strongest when aligned; rotating one relative to the other can increase loss. Circular polarization has a rotating field, but both ends should have compatible handedness. Assess mixed types using actual antenna specifications.

## Pattern and mounting

An omnidirectional antenna is not equally strong in every three-dimensional direction. It has weaker angles, and batteries or metal mounts can block parts of its pattern. A directional ground antenna needs accurate pointing. Coax loss and loose connectors may hide the real cause.

Peak gain concentrates radiation; it does not create transmitter power. Verify operating frequency, connector and impedance, and polarization before replacing an antenna. A mechanically fitting connector is not proof of RF compatibility.

## Diagnose with repeatable movement

Record signal and video while rotating or banking the aircraft in a controlled setup. Keep frequency and antenna positions consistent when comparing. Inspect orientation, polarization, connector seating and the clear view around each antenna. Distinguish a predictable attitude-related fade from random interference.

![ZYRO C403 Max digital video-link hardware](../../products/c403.jpg)

Proper placement and compatible polarization protect the link margin already available.`
  },
  {
    slug: "video-bitrate", tag: "Video transmission", title: "4K, 90 fps and Mbps: why resolution alone cannot describe a video link", date: "2026.07.23", read: "7 min read",
    deck: "Pixel count, frame rate, compression and radio capacity together determine useful video performance.",
    body: `# 4K, 90 fps and Mbps: why resolution alone cannot describe a video link

4K states image dimensions, not the bitrate required to send the picture or the time before it appears. More pixels can reveal more detail when the lens, sensor and image pipeline resolve it. Frame rate describes how frequently a new image is sampled: 30 fps corresponds to about 33.3 ms per frame, 60 fps to 16.7 ms and 90 fps to 11.1 ms.

Uncompressed 1080p60 at 24 bits per pixel contains almost 3 Gbit of pixel data per second, and 4K30 nearly 6 Gbit/s. These are raw-image calculations, not wireless bitrates. Compression makes practical video links possible.

## Compression and the radio link

H.265 can reduce bitrate for a given image-quality target, but its benefit depends on motion, encoder settings and buffering. Fast-moving scenes are harder to compress than static ones. Advertised peak radio throughput is not the same as sustainable video capacity. Protocol overhead, interference and retransmissions reduce usable capacity. When peak bitrate approaches available throughput, stalls or sudden quality reductions can follow.

## Compare modes fairly

Record resolution, frame rate, codec, average and peak bitrate, receiver settings and camera-to-screen delay. 1080p90 may offer more responsive motion than 4K30, while 4K30 can better support detailed observation. Choose according to the task and measured link margin, not resolution alone.

![ZYRO Air digital video-link product](../../products/air.jpg)`
  },
  {
    slug: "thermal-imaging", tag: "Thermal imaging", title: "How can thermal imaging see without visible light?", date: "2026.07.15", read: "8 min read",
    deck: "Thermal cameras detect emitted infrared radiation and turn differences into a visible image.",
    body: `# How can thermal imaging see without visible light?

Objects above absolute zero emit infrared radiation. A thermal sensor, often working around the 8–14 μm long-wave infrared band, measures it without needing reflected daylight. The displayed colors or brightness represent detected radiation, not a direct visible-light photograph or automatically accurate surface temperatures.

## What affects the reading?

Emissivity, reflected surroundings, humidity and distance matter. Shiny metal may reflect the environment and appear unexpectedly cool or warm. Temperature measurement needs calibration and suitable conditions.

## Four useful specifications

Infrared resolution counts actual thermal pixels; display resolution may only upscale them. NETD describes the ability to distinguish small temperature differences under defined conditions; lower NETD can help subtle contrast but is not a complete quality metric. Lens field of view sets coverage and the number of pixels on a target. Frame rate matters when the subject or platform moves.

Some modules use shutterless non-uniformity-correction algorithms intended to reduce interruption during mobile observation. “Shutterless” alone does not establish image stability or temperature accuracy; compare specific hardware and recorded footage.

## Choose for the mission

Define target size, distance and whether you need temperature measurement or detection. Compare real imagery at the intended range and conditions. Rain, fog, windows and some materials can reduce or block long-wave infrared information. Visible-light context can help identify what a thermal shape represents.

![ZYRO thermal-imaging series](../../products/thermal.jpg)`
  },
  {
    slug: "latency", tag: "Video-link fundamentals", title: "2 ms, 35 ms and one frame: where does latency come from?", date: "2026.07.13", read: "7 min read",
    deck: "Radio round-trip time and camera-to-screen delay measure different parts of a video system.",
    body: `# 2 ms, 35 ms and one frame: where does latency come from?

A frame passes through camera exposure and readout, image processing, encoding, wireless transfer, decoding and display. ZYRO Link's brief cites typical radio round-trip time as low as 2 ms; ZYRO Cam's brief cites end-to-end image latency as low as 35 ms. Their measurement boundaries differ, so the figures cannot be compared directly.

## Follow the whole frame

Total delay is approximately capture + processing + encoding + wireless transfer + decoding and display. Buffers, retransmissions and a monitor refresh can add delay or jitter even when the radio stage is fast.

Digital links commonly spend time encoding and decoding. H.265 can improve quality at a given bitrate, but buffering and receiver performance affect delay. Analog video avoids complex compression and can provide a shorter image path while generally trading away some resolution and spectrum efficiency.

## Frame timing

A single interval lasts about 33.3 ms at 30 fps, 16.7 ms at 60 fps and 11.1 ms at 90 fps. If any stage waits one full frame, that interval contributes to the total. Higher frame rate can shorten the wait for the next frame, but increases processing and bitrate demand.

| Video mode | Approximate frame interval | Main priority |
| --- | --- | --- |
| 4K30 | 33.3 ms | Detail |
| 1080p60 | 16.7 ms | Detail and response |
| 1080p90 | 11.1 ms | Fast feedback |

## Measure the visible result

State whether the test measures network RTT or light entering the camera to a picture appearing on screen. Fix resolution, codec, frame rate and bitrate. Film a timing reference and the receiving display using a common clock, then report a range and jitter rather than only a minimum value.

![ZYRO Air digital video-link product](../../products/air.jpg)`
  },
  {
    slug: "mesh-networking", tag: "Networking fundamentals", title: "Why Mesh networks suit mobile systems and emergency sites", date: "2026.07.06", read: "8 min read",
    deck: "Compatible nodes can create and change forwarding paths when a direct link is obstructed.",
    body: `# Why Mesh networks suit mobile systems and emergency sites

At mobile sites, terrain, buildings or vehicles may interrupt a fixed link. A Mesh system lets compatible nodes exchange data and, where supported, relay it through another node.

## Nodes and alternate paths

A node may send directly or use one or more relay hops. As nodes move or leave, the network can establish another available relationship if coverage and configuration permit. This is useful for a distributed field site, but it does not ensure that every node always stays connected.

## Relays consume airtime

A relay must receive data and then transmit it. On a shared half-duplex channel, forwarding occupies additional airtime and can lower usable throughput or increase delay. Multiple video streams share this capacity; summing encoded bitrates alone ignores overhead and margin.

A practical plan has four stages: map node roles; estimate streams and relay airtime; check frequency, antennas, heights and obstructions; and test direct and relay paths while nodes move. Record recovery behavior, not only static connectivity.

## Plan and measure

List node roles, frequency, expected stream rates and likely obstructions. Check antenna height and line of sight. Test direct and relayed paths separately; then move nodes through realistic positions while measuring throughput, loss and recovery time. A ZYRO Link point-to-multipoint test and a multi-hop MESH report describe different arrangements, each with its own test conditions.

![ZYRO Mesh product](../../products/mesh.jpg)`
  },
  {
    slug: "link-budget", tag: "RF fundamentals", title: "Transmit power is not range: four link-budget variables", date: "2026.06.29", read: "6 min read",
    deck: "Frequency, antennas, receiver sensitivity and environment jointly determine usable radio margin.",
    body: `# Transmit power is not range: four link-budget variables

A larger transmitter-power number cannot predict the usable distance of a video link by itself. Signal arriving at the receiver depends on the whole path and on whether the receiver can decode it with sufficient margin.

## Account for gain and loss

A simplified calculation adds transmit power and antenna gains, then subtracts path and other losses: received power ≈ transmit power + transmit antenna gain + receive antenna gain − path loss − other loss. Distance and frequency affect free-space loss. Obstructions, polarization mismatch, feed-line loss and interference can make a real result worse than an ideal calculation.

Power is logarithmic: doubling transmit power adds about 3 dB, not twice the distance. At a fixed distance, doubling frequency raises ideal free-space path loss by about 6 dB. Antenna gain recovers margin only in the directions where that gain applies.

## Sensitivity and margin

Receiver sensitivity is a threshold under particular bitrate and error conditions. The amount by which the received signal exceeds that threshold is link margin. Increasing bitrate or bandwidth may change the threshold. Extra margin helps a mobile link tolerate fades from motion or partial obstruction.

## Four field questions

What frequency and bandwidth are used? What are the installed antenna patterns and cable losses? Which sensitivity figure applies to the target video rate? What terrain, height, foliage and RF noise lie on the path? Record these answers, then measure signal and throughput at repeatable locations before extrapolating coverage.

Before testing, record transmitter power, frequency, bandwidth, both installed antennas, receiver mode and sensitivity, path geometry and height, and local interference. A range result without these conditions cannot reliably be transferred to another route.

![3 W RF transmitter module](../../products/tx3w.jpg)`
  },
];
